// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PairMatcher.DAL;

#nullable disable

namespace PairMatcher.Migrations
{
    [DbContext(typeof(PairMatcherDbContext))]
    [Migration("20230523073007_studentpair column added")]
    partial class studentpaircolumnadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PairMatcher.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PairStudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PairStudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PairMatcher.Student", b =>
                {
                    b.HasOne("PairMatcher.Student", "PairStudent")
                        .WithMany()
                        .HasForeignKey("PairStudentId");

                    b.Navigation("PairStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
